name: Deployment to KVM
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: 'root'
          key: ${{ secrets.DEPLOY_KEY }}
          script: >
            cd /var/www/discord-bot &&
            git config --global --add safe.directory /var/www/discord-bot &&
            git pull &&
            bun install &&
            pm2 reload discord-bot ||
            pm2 start --name discord-bot --cwd /var/www/discord-bot -c "bun src/index.ts" &&
            pm2 save